using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Analyser
{
    public static class Folderlist
    {
        public static List<String> GetFolderlist()
        {
            return new List<String>()
            {
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm baseline",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_10_v1.61",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_09_v1.62",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_08_v1.63",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_07_v1.64",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_06_v1.65",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_05_v1.66",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_04_v1.67",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_03_v1.68",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_02_v1.69",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_01_v1.610",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_11_v1.611",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_12_v1.612",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_13_v1.613",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_14_v1.614",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_15_v1.615",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_16_v1.616",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_17_v1.617",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_18_v1.618",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_19_v1.619",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_20_v1.620",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_wo-zl_01_v1.81",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_wo-zl_02_v1.82",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_wo-zl_03_v1.83",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_wo-zl_04_v1.84",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_wo-zl_05_v1.85",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_wo-zl_06_v1.86",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_wo-zl_07_v1.87",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_wo-zl_08_v1.88",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_wo-zl_09_v1.89",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm v2bagging_wo-zl_10_v1.810",
                ////@"D:\Sciebo\TT\Ensemble Results\c2k\stateless cudnn nosubsequences",
                ////@"C:\TT\Ensemble Results\tt\v2.11",
                ////@"C:\TT\Ensemble Results\tt\v2.12",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 100 1",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 100 2",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 100 3",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 100 4",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 100 5",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 200 1",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 200 2",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 200 3",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 200 4",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 200 5",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 300 1",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 300 2",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 300 3",
                //@"C:\TT\Ensemble Results\c2k\stateless networksize 300 4",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm clipvalue 0.1",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm clipvalue 0.2",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm clipvalue 0.4",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm clipvalue 0.8",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm clipvalue 1.6",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm clipvalue 3.2",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm clipvalue 6.4",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm clipvalue 12.8",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm batch_size 1",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm batch_size 2",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm batch_size 4",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm batch_size 8",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm batch_size 16",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm batch_size 32",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm batch_size 64",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm batch_size 128",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn lstm batch_size 256",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn gru",
                //@"C:\TT\Ensemble Results\c2k\stateless gru",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm nolabel",
                //@"C:\TT\Ensemble Results\c2k\stateless rnn",
                //@"C:\TT\Ensemble Results\c2k\test",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 100 1",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 100 2",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 100 3",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 100 4",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 100 5",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 200 1",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 200 2",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 200 3",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 200 4",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 200 5",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 300 1",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 300 2",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 300 3",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 300 4",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 300 5",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 400 1",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 400 2",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 400 3",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 400 4",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 400 5",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 500 1",
                //@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 500 2",
                ////@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 500 3",
                ////@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 500 4",
                ////@"C:\TT\Ensemble Results\c2k\stateless cudnn networksize 500 5",  
                //@"C:\TT\Ensemble Results\c2k\stateless lstm batch_size 1",
                //@"C:\TT\Ensemble Results\c2k\stateless lstm batch_size 2",

                @"C:\TT\Ensemble Results\c2k\stateless lstm clipvalue 0.1",
                @"C:\TT\Ensemble Results\c2k\stateless lstm clipvalue 0.2",
                @"C:\TT\Ensemble Results\c2k\stateless lstm clipvalue 0.4",
            };
        }
    }
}
